prove:		
	export SPARKLIB_OBJECT_DIR="sparklibobj" && \
	gnatprove -Pmlkem -u src/mylemmas.adb
	export SPARKLIB_OBJECT_DIR="sparklibobj" && \
	gnatprove -Pmlkem -u src/mlkem.adb
compile:
	export SPARKLIB_OBJECT_DIR="sparklibobj" && \
	gprbuild -Pmlkem

